name = "Academic"
license = "MIT"
licenselink = "https://github.com/wowchemy/starter-hugo-academic/blob/master/LICENSE.md"
description = "Pierre Beaucoral personnal website. PhD student which research interests include development economics, climate adaptation and mitigation, environment, development and climate finance."
homepage = "https://pierrebeaucoral.github.io/"
demosite = "https://wowchemy.com/hugo-themes/"
tags = ["widgets",
        "resume",
        "portfolio",
        "responsive",
        "clean",
        "personal",
        "company",
        "blog",
        "minimal",
        "light",
        "dark",
        "multilingual",
        "documentation",
        "landing page",
        "projects",
        "single page",
        "contact form",
        "mobile",
        "gallery",
        "search",
        "presentation",
        "simple",
        "minimalist",
        "starter",
        "modern",
        "one page",
        "customizable",
        "technical",
        "product",
        "slide", 
        "Development", 
        "Climate", 
        "Finance", 
        "Environnement", 
        "Machine learning",
        "International financial flows", 
        "Economics",
        "Research", 
        "Academic"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "Pierre Beaucoral"
  homepage = "https://pierrebeaucoral.github.io/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
